import type { PC } from "@/types/pc";
import type { Device } from "@/types/device";

export const MOCK_PCS: PC[] = [
  {
    id: "1",
    slug: "gaming-beast-rtx4090",
    name: "Gaming Beast RTX 4090",
    price: 450000,
    description: "Топовая игровая сборка для 4K гейминга",
    quality: "4K",
    thumbnail: "https://placehold.co/400x300/1a1a1a/00ff00?text=RTX+4090",
    gallery: [
      { id: "1-1", url: "https://placehold.co/800x600/1a1a1a/00ff00?text=Front", alt: "Front view" },
      { id: "1-2", url: "https://placehold.co/800x600/1a1a1a/00ff00?text=Side", alt: "Side view" },
      { id: "1-3", url: "https://placehold.co/800x600/1a1a1a/00ff00?text=Inside", alt: "Inside view" },
    ],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    specs: [
      { label: "Процессор", value: "Intel Core i9-14900K" },
      { label: "Видеокарта", value: "NVIDIA GeForce RTX 4090 24GB" },
      { label: "Материнская плата", value: "ASUS ROG MAXIMUS Z790 HERO" },
      { label: "Охлаждение", value: "Arctic Liquid Freezer II 360" },
      { label: "Блок питания", value: "Corsair HX1200 1200W 80+ Platinum" },
      { label: "Корпус", value: "Lian Li O11 Dynamic EVO" },
    ],
    configOptions: {
      ram: [
        { id: "ram-32", label: "32GB DDR5-6000", priceDelta: 0, default: true },
        { id: "ram-64", label: "64GB DDR5-6000", priceDelta: 15000 },
        { id: "ram-96", label: "96GB DDR5-6000", priceDelta: 30000 },
      ],
      ssd: [
        { id: "ssd-1tb", label: "1TB NVMe Gen4", priceDelta: 0, default: true },
        { id: "ssd-2tb", label: "2TB NVMe Gen4", priceDelta: 8000 },
        { id: "ssd-4tb", label: "4TB NVMe Gen4", priceDelta: 20000 },
      ],
    },
    featured: true,
  },
  {
    id: "2",
    slug: "mid-tier-rtx4070super",
    name: "Mid-Tier RTX 4070 Super",
    price: 180000,
    description: "Оптимальная сборка для 2K гейминга",
    quality: "2K",
    thumbnail: "https://placehold.co/400x300/1a1a1a/0099ff?text=RTX+4070S",
    gallery: [
      { id: "2-1", url: "https://placehold.co/800x600/1a1a1a/0099ff?text=Front", alt: "Front view" },
      { id: "2-2", url: "https://placehold.co/800x600/1a1a1a/0099ff?text=Side", alt: "Side view" },
    ],
    specs: [
      { label: "Процессор", value: "AMD Ryzen 7 7800X3D" },
      { label: "Видеокарта", value: "NVIDIA GeForce RTX 4070 Super 12GB" },
      { label: "Материнская плата", value: "MSI MAG B650 TOMAHAWK" },
      { label: "ОЗУ", value: "32GB DDR5-6000" },
      { label: "Охлаждение", value: "DeepCool AK620" },
      { label: "SSD", value: "1TB Samsung 980 Pro" },
      { label: "Блок питания", value: "Be Quiet! Pure Power 11 750W 80+ Gold" },
      { label: "Корпус", value: "Fractal Design Meshify 2" },
    ],
    configOptions: {
      ram: [
        { id: "ram-16", label: "16GB DDR5-6000", priceDelta: -8000 },
        { id: "ram-32", label: "32GB DDR5-6000", priceDelta: 0, default: true },
        { id: "ram-64", label: "64GB DDR5-6000", priceDelta: 12000 },
      ],
      ssd: [
        { id: "ssd-500gb", label: "500GB NVMe Gen4", priceDelta: -4000 },
        { id: "ssd-1tb", label: "1TB NVMe Gen4", priceDelta: 0, default: true },
        { id: "ssd-2tb", label: "2TB NVMe Gen4", priceDelta: 7000 },
      ],
    },
    featured: true,
  },
  {
    id: "3",
    slug: "budget-rtx4060",
    name: "Budget RTX 4060",
    price: 95000,
    description: "Доступная сборка для Full HD гейминга",
    quality: "FHD",
    thumbnail: "https://placehold.co/400x300/1a1a1a/ff9900?text=RTX+4060",
    gallery: [
      { id: "3-1", url: "https://placehold.co/800x600/1a1a1a/ff9900?text=Front", alt: "Front view" },
    ],
    specs: [
      { label: "Процессор", value: "AMD Ryzen 5 7600" },
      { label: "Видеокарта", value: "NVIDIA GeForce RTX 4060 8GB" },
      { label: "Материнская плата", value: "ASRock B650M Pro RS" },
      { label: "ОЗУ", value: "16GB DDR5-5600" },
      { label: "Охлаждение", value: "ID-Cooling SE-224-XT" },
      { label: "SSD", value: "512GB Kingston NV2" },
      { label: "Блок питания", value: "Chieftec Proton 600W 80+ Bronze" },
      { label: "Корпус", value: "DeepCool MATREXX 40" },
    ],
    configOptions: {
      ram: [
        { id: "ram-8", label: "8GB DDR5-5600", priceDelta: -4000 },
        { id: "ram-16", label: "16GB DDR5-5600", priceDelta: 0, default: true },
        { id: "ram-32", label: "32GB DDR5-5600", priceDelta: 7000 },
      ],
      ssd: [
        { id: "ssd-256gb", label: "256GB NVMe", priceDelta: -2000 },
        { id: "ssd-512gb", label: "512GB NVMe", priceDelta: 0, default: true },
        { id: "ssd-1tb", label: "1TB NVMe", priceDelta: 3500 },
      ],
    },
    featured: true,
  },
  {
    id: "4",
    slug: "workstation-pro",
    name: "Workstation Pro",
    price: 280000,
    description: "Профессиональная рабочая станция",
    quality: "2K",
    thumbnail: "https://placehold.co/400x300/1a1a1a/9900ff?text=Workstation",
    gallery: [
      { id: "4-1", url: "https://placehold.co/800x600/1a1a1a/9900ff?text=Front", alt: "Front view" },
    ],
    specs: [
      { label: "Процессор", value: "AMD Ryzen 9 7950X" },
      { label: "Видеокарта", value: "NVIDIA RTX 4080 16GB" },
      { label: "Материнская плата", value: "ASUS ProArt X670E-CREATOR" },
      { label: "ОЗУ", value: "64GB DDR5-6000" },
      { label: "Охлаждение", value: "Noctua NH-D15 chromax.black" },
      { label: "SSD", value: "2TB Samsung 990 Pro" },
      { label: "Блок питания", value: "Seasonic PRIME TX-1000 1000W 80+ Titanium" },
      { label: "Корпус", value: "be quiet! Dark Base Pro 900" },
    ],
    configOptions: {
      ram: [
        { id: "ram-64", label: "64GB DDR5-6000", priceDelta: 0, default: true },
        { id: "ram-128", label: "128GB DDR5-6000", priceDelta: 40000 },
      ],
      ssd: [
        { id: "ssd-2tb", label: "2TB NVMe Gen4", priceDelta: 0, default: true },
        { id: "ssd-4tb", label: "4TB NVMe Gen4", priceDelta: 18000 },
      ],
    },
    featured: true,
  },
  {
    id: "5",
    slug: "entry-level-rx6600",
    name: "Entry Level RX 6600",
    price: 65000,
    description: "Начальная игровая сборка",
    quality: "FHD",
    thumbnail: "https://placehold.co/400x300/1a1a1a/ff0066?text=RX+6600",
    gallery: [
      { id: "5-1", url: "https://placehold.co/800x600/1a1a1a/ff0066?text=Build", alt: "Build view" },
    ],
    specs: [
      { label: "Процессор", value: "AMD Ryzen 5 5600" },
      { label: "Видеокарта", value: "AMD Radeon RX 6600 8GB" },
      { label: "Материнская плата", value: "MSI B550M PRO-VDH" },
      { label: "ОЗУ", value: "16GB DDR4-3200" },
      { label: "Охлаждение", value: "Arctic Freezer 34 eSports" },
      { label: "SSD", value: "512GB WD Blue SN570" },
      { label: "Блок питания", value: "EVGA 600 W1 600W 80+" },
      { label: "Корпус", value: "Zalman S2" },
    ],
    configOptions: {
      ram: [
        { id: "ram-8", label: "8GB DDR4-3200", priceDelta: -3000 },
        { id: "ram-16", label: "16GB DDR4-3200", priceDelta: 0, default: true },
        { id: "ram-32", label: "32GB DDR4-3200", priceDelta: 5000 },
      ],
      ssd: [
        { id: "ssd-256gb", label: "256GB SATA", priceDelta: -2000 },
        { id: "ssd-512gb", label: "512GB NVMe", priceDelta: 0, default: true },
        { id: "ssd-1tb", label: "1TB NVMe", priceDelta: 3000 },
      ],
    },
  },
  {
    id: "6",
    slug: "premium-rtx4080super",
    name: "Premium RTX 4080 Super",
    price: 320000,
    description: "Премиум сборка для 4K гейминга",
    quality: "4K",
    thumbnail: "https://placehold.co/400x300/1a1a1a/00ffff?text=RTX+4080S",
    gallery: [
      { id: "6-1", url: "https://placehold.co/800x600/1a1a1a/00ffff?text=RGB", alt: "RGB view" },
    ],
    specs: [
      { label: "Процессор", value: "Intel Core i7-14700K" },
      { label: "Видеокарта", value: "NVIDIA GeForce RTX 4080 Super 16GB" },
      { label: "Материнская плата", value: "ASUS ROG STRIX Z790-E GAMING" },
      { label: "ОЗУ", value: "32GB DDR5-6400" },
      { label: "Охлаждение", value: "NZXT Kraken X73 RGB" },
      { label: "SSD", value: "2TB Crucial T700" },
      { label: "Блок питания", value: "Corsair RM1000x 1000W 80+ Gold" },
      { label: "Корпус", value: "NZXT H7 Flow" },
    ],
    configOptions: {
      ram: [
        { id: "ram-32", label: "32GB DDR5-6400", priceDelta: 0, default: true },
        { id: "ram-64", label: "64GB DDR5-6400", priceDelta: 18000 },
      ],
      ssd: [
        { id: "ssd-1tb", label: "1TB NVMe Gen5", priceDelta: -6000 },
        { id: "ssd-2tb", label: "2TB NVMe Gen5", priceDelta: 0, default: true },
        { id: "ssd-4tb", label: "4TB NVMe Gen5", priceDelta: 25000 },
      ],
    },
  },
];

export const MOCK_DEVICES: Device[] = [
  {
    id: "d1",
    slug: "samsung-odyssey-g7",
    name: "Samsung Odyssey G7 32\"",
    price: 45000,
    description: "2K 240Hz игровой монитор",
    category: "monitor",
    thumbnail: "https://placehold.co/400x300/1a1a1a/ffffff?text=Monitor",
    featured: true,
  },
  {
    id: "d2",
    slug: "keychron-q1-pro",
    name: "Keychron Q1 Pro",
    price: 18000,
    description: "Механическая клавиатура 75%",
    category: "keyboard",
    thumbnail: "https://placehold.co/400x300/1a1a1a/ffffff?text=Keyboard",
    featured: true,
  },
  {
    id: "d3",
    slug: "logitech-g-pro-x-superlight",
    name: "Logitech G Pro X Superlight",
    price: 12000,
    description: "Беспроводная игровая мышь",
    category: "mouse",
    thumbnail: "https://placehold.co/400x300/1a1a1a/ffffff?text=Mouse",
    featured: true,
  },
  {
    id: "d4",
    slug: "steelseries-arctis-nova-pro",
    name: "SteelSeries Arctis Nova Pro",
    price: 28000,
    description: "Премиум игровая гарнитура",
    category: "headset",
    thumbnail: "https://placehold.co/400x300/1a1a1a/ffffff?text=Headset",
    featured: true,
  },
  {
    id: "d5",
    slug: "secretlab-titan-evo",
    name: "Secretlab Titan Evo 2022",
    price: 55000,
    description: "Премиум игровое кресло",
    category: "chair",
    thumbnail: "https://placehold.co/400x300/1a1a1a/ffffff?text=Chair",
  },
  {
    id: "d6",
    slug: "lg-27gp950",
    name: "LG 27GP950-B",
    price: 65000,
    description: "4K 144Hz HDR игровой монитор",
    category: "monitor",
    thumbnail: "https://placehold.co/400x300/1a1a1a/ffffff?text=4K+Monitor",
  },
];
